Keras를 사용한 회귀 모델

In [1]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [2]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
concrete_data.shape

(1030, 9)

In [4]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [5]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [7]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [8]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [9]:
n_cols = predictors_norm.shape[1] # number of predictors

In [10]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

In [11]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [12]:
# build the model
model = regression_model()

In [13]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 0s - 21ms/step - loss: 1650.0338 - val_loss: 1141.6110
Epoch 2/100
23/23 - 0s - 3ms/step - loss: 1499.0872 - val_loss: 1008.1505
Epoch 3/100
23/23 - 0s - 3ms/step - loss: 1268.0593 - val_loss: 806.1599
Epoch 4/100
23/23 - 0s - 3ms/step - loss: 940.3928 - val_loss: 562.5379
Epoch 5/100
23/23 - 0s - 3ms/step - loss: 590.4465 - val_loss: 341.3156
Epoch 6/100
23/23 - 0s - 3ms/step - loss: 351.2916 - val_loss: 216.5077
Epoch 7/100
23/23 - 0s - 3ms/step - loss: 265.0482 - val_loss: 177.6889
Epoch 8/100
23/23 - 0s - 3ms/step - loss: 239.5686 - val_loss: 165.7264
Epoch 9/100
23/23 - 0s - 3ms/step - loss: 223.9066 - val_loss: 161.5533
Epoch 10/100
23/23 - 0s - 3ms/step - loss: 211.8390 - val_loss: 155.9751
Epoch 11/100
23/23 - 0s - 3ms/step - loss: 202.4180 - val_loss: 153.6110
Epoch 12/100
23/23 - 0s - 3ms/step - loss: 195.3493 - val_loss: 151.0360
Epoch 13/100
23/23 - 0s - 3ms/step - loss: 189.5350 - val_loss: 150.4411
Epoch 14/100
23/23 - 0s - 3ms/step - loss: 183.4924 - val_loss: 147.0734
Epoch 15/100
23/23 - 0s - 3ms/step - loss: 178.7518 - val_loss: 144.9827
Epoch 16/100
23/23 - 0s - 3ms/step - loss: 174.1766 - val_loss: 145.5617
Epoch 17/100
23/23 - 0s - 3ms/step - loss: 170.7249 - val_loss: 142.8838
Epoch 18/100
23/23 - 0s - 3ms/step - loss: 167.1353 - val_loss: 145.0845
Epoch 19/100
23/23 - 0s - 3ms/step - loss: 164.4335 - val_loss: 142.5192
Epoch 20/100
23/23 - 0s - 3ms/step - loss: 161.2674 - val_loss: 141.9128
Epoch 21/100
23/23 - 0s - 3ms/step - loss: 159.2398 - val_loss: 140.8400
Epoch 22/100
23/23 - 0s - 3ms/step - loss: 156.2911 - val_loss: 140.7226
Epoch 23/100
23/23 - 0s - 3ms/step - loss: 154.1937 - val_loss: 141.5459
Epoch 24/100
23/23 - 0s - 3ms/step - loss: 151.8438 - val_loss: 140.2087
Epoch 25/100
23/23 - 0s - 3ms/step - loss: 149.9772 - val_loss: 142.5075
Epoch 26/100
23/23 - 0s - 3ms/step - loss: 147.8108 - val_loss: 139.8102
Epoch 27/100
23/23 - 0s - 3ms/step - loss: 146.2163 - val_loss: 141.7124
Epoch 28/100
23/23 - 0s - 3ms/step - loss: 144.4105 - val_loss: 141.9980
Epoch 29/100
23/23 - 0s - 3ms/step - loss: 142.5893 - val_loss: 141.6722
Epoch 30/100
23/23 - 0s - 3ms/step - loss: 141.4165 - val_loss: 144.8700
Epoch 31/100
23/23 - 0s - 3ms/step - loss: 139.7558 - val_loss: 140.7484
Epoch 32/100
23/23 - 0s - 2ms/step - loss: 138.2925 - val_loss: 143.0300
Epoch 33/100
23/23 - 0s - 3ms/step - loss: 136.9267 - val_loss: 142.3833
Epoch 34/100
23/23 - 0s - 3ms/step - loss: 135.3851 - val_loss: 143.4580
Epoch 35/100
23/23 - 0s - 3ms/step - loss: 134.3098 - val_loss: 143.6718
Epoch 36/100
23/23 - 0s - 3ms/step - loss: 132.8746 - val_loss: 144.8276
Epoch 37/100
23/23 - 0s - 3ms/step - loss: 131.7294 - val_loss: 143.4049
Epoch 38/100
23/23 - 0s - 3ms/step - loss: 130.3678 - val_loss: 143.0368
Epoch 39/100
23/23 - 0s - 3ms/step - loss: 129.8261 - val_loss: 144.7435
Epoch 40/100
23/23 - 0s - 3ms/step - loss: 128.1508 - val_loss: 142.4459
Epoch 41/100
23/23 - 0s - 3ms/step - loss: 126.5271 - val_loss: 140.9000
Epoch 42/100
23/23 - 0s - 3ms/step - loss: 125.3002 - val_loss: 145.5093
Epoch 43/100
23/23 - 0s - 3ms/step - loss: 123.5456 - val_loss: 140.4166
Epoch 44/100
23/23 - 0s - 3ms/step - loss: 121.7841 - val_loss: 142.0508
Epoch 45/100
23/23 - 0s - 3ms/step - loss: 119.4579 - val_loss: 144.4944
Epoch 46/100
23/23 - 0s - 3ms/step - loss: 117.4299 - val_loss: 143.3857
Epoch 47/100
23/23 - 0s - 3ms/step - loss: 115.1664 - val_loss: 145.6565
Epoch 48/100
23/23 - 0s - 2ms/step - loss: 113.8499 - val_loss: 144.2027
Epoch 49/100
23/23 - 0s - 3ms/step - loss: 112.7145 - val_loss: 145.9920
Epoch 50/100
23/23 - 0s - 3ms/step - loss: 109.4151 - val_loss: 141.7780
Epoch 51/100
23/23 - 0s - 3ms/step - loss: 107.0364 - val_loss: 145.4554
Epoch 52/100
23/23 - 0s - 3ms/step - loss: 104.9001 - val_loss: 142.9965
Epoch 53/100
23/23 - 0s - 3ms/step - loss: 102.6366 - val_loss: 143.9142
Epoch 54/100
23/23 - 0s - 3ms/step - loss: 98.9913 - val_loss: 145.2426
Epoch 55/100
23/23 - 0s - 3ms/step - loss: 96.1954 - val_loss: 139.7746
Epoch 56/100
23/23 - 0s - 3ms/step - loss: 93.5218 - val_loss: 144.0466
Epoch 57/100
23/23 - 0s - 3ms/step - loss: 90.8931 - val_loss: 136.2369
Epoch 58/100
23/23 - 0s - 3ms/step - loss: 87.3138 - val_loss: 142.3439
Epoch 59/100
23/23 - 0s - 2ms/step - loss: 84.4277 - val_loss: 137.3707
Epoch 60/100
23/23 - 0s - 3ms/step - loss: 81.0840 - val_loss: 140.8385
Epoch 61/100
23/23 - 0s - 3ms/step - loss: 78.5718 - val_loss: 134.8296
Epoch 62/100
23/23 - 0s - 3ms/step - loss: 75.0016 - val_loss: 131.6895
Epoch 63/100
23/23 - 0s - 3ms/step - loss: 73.2121 - val_loss: 139.1032
Epoch 64/100
23/23 - 0s - 3ms/step - loss: 70.1652 - val_loss: 124.3952
Epoch 65/100
23/23 - 0s - 3ms/step - loss: 67.7958 - val_loss: 134.0341
Epoch 66/100
23/23 - 0s - 3ms/step - loss: 63.8339 - val_loss: 129.7543
Epoch 67/100
23/23 - 0s - 3ms/step - loss: 61.4887 - val_loss: 126.1072
Epoch 68/100
23/23 - 0s - 3ms/step - loss: 59.1955 - val_loss: 122.3370
Epoch 69/100
23/23 - 0s - 3ms/step - loss: 58.8492 - val_loss: 136.5817
Epoch 70/100
23/23 - 0s - 3ms/step - loss: 55.5950 - val_loss: 120.2048
Epoch 71/100
23/23 - 0s - 3ms/step - loss: 53.7483 - val_loss: 122.1951
Epoch 72/100
23/23 - 0s - 3ms/step - loss: 51.9492 - val_loss: 124.3468
Epoch 73/100
23/23 - 0s - 3ms/step - loss: 50.8588 - val_loss: 122.4985
Epoch 74/100
23/23 - 0s - 3ms/step - loss: 49.7621 - val_loss: 121.5971
Epoch 75/100
23/23 - 0s - 3ms/step - loss: 48.4849 - val_loss: 116.2514
Epoch 76/100
23/23 - 0s - 3ms/step - loss: 46.7085 - val_loss: 121.3055
Epoch 77/100
23/23 - 0s - 3ms/step - loss: 46.3423 - val_loss: 120.8741
Epoch 78/100
23/23 - 0s - 3ms/step - loss: 45.1932 - val_loss: 116.6839
Epoch 79/100
23/23 - 0s - 3ms/step - loss: 44.0813 - val_loss: 117.3412
Epoch 80/100
23/23 - 0s - 3ms/step - loss: 43.0778 - val_loss: 115.1261
Epoch 81/100
23/23 - 0s - 3ms/step - loss: 42.7581 - val_loss: 115.5894
Epoch 82/100
23/23 - 0s - 3ms/step - loss: 41.1798 - val_loss: 130.5461
Epoch 83/100
23/23 - 0s - 3ms/step - loss: 41.0882 - val_loss: 110.2578
Epoch 84/100
23/23 - 0s - 3ms/step - loss: 40.0059 - val_loss: 120.5061
Epoch 85/100
23/23 - 0s - 3ms/step - loss: 40.2386 - val_loss: 119.2029
Epoch 86/100
23/23 - 0s - 3ms/step - loss: 39.2987 - val_loss: 118.6974
Epoch 87/100
23/23 - 0s - 3ms/step - loss: 38.9822 - val_loss: 115.6073
Epoch 88/100
23/23 - 0s - 3ms/step - loss: 38.6077 - val_loss: 110.7114
Epoch 89/100
23/23 - 0s - 3ms/step - loss: 37.4489 - val_loss: 122.7561
Epoch 90/100
23/23 - 0s - 3ms/step - loss: 37.5334 - val_loss: 119.0201
Epoch 91/100
23/23 - 0s - 3ms/step - loss: 36.4382 - val_loss: 123.7552
Epoch 92/100
23/23 - 0s - 3ms/step - loss: 36.6106 - val_loss: 126.2371
Epoch 93/100
23/23 - 0s - 3ms/step - loss: 35.8960 - val_loss: 122.6034
Epoch 94/100
23/23 - 0s - 3ms/step - loss: 35.3376 - val_loss: 118.1847
Epoch 95/100
23/23 - 0s - 3ms/step - loss: 34.7216 - val_loss: 123.5378
Epoch 96/100
23/23 - 0s - 3ms/step - loss: 35.4140 - val_loss: 116.9859
Epoch 97/100
23/23 - 0s - 3ms/step - loss: 34.4634 - val_loss: 125.4323
Epoch 98/100
23/23 - 0s - 3ms/step - loss: 34.2313 - val_loss: 110.5304
Epoch 99/100
23/23 - 0s - 3ms/step - loss: 34.1195 - val_loss: 112.9022
Epoch 100/100
23/23 - 0s - 3ms/step - loss: 33.3488 - val_loss: 116.5040

In [14]:
def regression_model():
    input_colm = predictors_norm.shape[1] # Number of input features
    # create model
    model = Sequential()
    model.add(Input(shape=(input_colm,)))  # Set the number of input features 
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu')) 
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(1))  # Output layer
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [15]:
# build the model
model = regression_model()
model.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

Epoch 1/100
29/29 - 1s - 23ms/step - loss: 1462.0336 - val_loss: 840.4232
Epoch 2/100
29/29 - 0s - 2ms/step - loss: 506.9443 - val_loss: 213.7798
Epoch 3/100
29/29 - 0s - 2ms/step - loss: 220.5878 - val_loss: 190.8328
Epoch 4/100
29/29 - 0s - 2ms/step - loss: 192.4791 - val_loss: 189.3685
Epoch 5/100
29/29 - 0s - 2ms/step - loss: 174.2199 - val_loss: 176.6422
Epoch 6/100
29/29 - 0s - 2ms/step - loss: 161.8863 - val_loss: 170.6436
Epoch 7/100
29/29 - 0s - 2ms/step - loss: 148.9161 - val_loss: 151.0284
Epoch 8/100
29/29 - 0s - 2ms/step - loss: 135.2515 - val_loss: 141.4593
Epoch 9/100
29/29 - 0s - 2ms/step - loss: 122.5993 - val_loss: 121.8757
Epoch 10/100
29/29 - 0s - 2ms/step - loss: 107.3171 - val_loss: 117.3344
Epoch 11/100
29/29 - 0s - 2ms/step - loss: 96.8145 - val_loss: 97.2836
Epoch 12/100
29/29 - 0s - 2ms/step - loss: 85.6363 - val_loss: 77.7015
Epoch 13/100
29/29 - 0s - 3ms/step - loss: 76.0493 - val_loss: 77.1964
Epoch 14/100
29/29 - 0s - 3ms/step - loss: 68.9207 - val_loss: 78.1790
Epoch 15/100
29/29 - 0s - 2ms/step - loss: 66.3811 - val_loss: 59.8159
Epoch 16/100
29/29 - 0s - 3ms/step - loss: 60.2448 - val_loss: 59.1114
Epoch 17/100
29/29 - 0s - 2ms/step - loss: 55.6755 - val_loss: 54.4066
Epoch 18/100
29/29 - 0s - 2ms/step - loss: 51.9486 - val_loss: 52.1180
Epoch 19/100
29/29 - 0s - 2ms/step - loss: 49.1757 - val_loss: 44.4581
Epoch 20/100
29/29 - 0s - 3ms/step - loss: 44.4347 - val_loss: 39.0289
Epoch 21/100
29/29 - 0s - 2ms/step - loss: 41.4883 - val_loss: 37.6579
Epoch 22/100
29/29 - 0s - 2ms/step - loss: 38.6529 - val_loss: 37.9922
Epoch 23/100
29/29 - 0s - 2ms/step - loss: 36.6457 - val_loss: 35.4981
Epoch 24/100
29/29 - 0s - 2ms/step - loss: 36.2330 - val_loss: 32.4652
Epoch 25/100
29/29 - 0s - 2ms/step - loss: 33.7344 - val_loss: 28.7937
Epoch 26/100
29/29 - 0s - 2ms/step - loss: 34.5295 - val_loss: 29.7014
Epoch 27/100
29/29 - 0s - 2ms/step - loss: 31.9973 - val_loss: 29.5220
Epoch 28/100
29/29 - 0s - 2ms/step - loss: 30.7469 - val_loss: 29.6317
Epoch 29/100
29/29 - 0s - 2ms/step - loss: 29.0010 - val_loss: 26.3170
Epoch 30/100
29/29 - 0s - 2ms/step - loss: 26.6109 - val_loss: 26.2982
Epoch 31/100
29/29 - 0s - 3ms/step - loss: 25.9463 - val_loss: 23.6025
Epoch 32/100
29/29 - 0s - 2ms/step - loss: 25.9848 - val_loss: 24.9708
Epoch 33/100
29/29 - 0s - 3ms/step - loss: 24.7984 - val_loss: 24.7816
Epoch 34/100
29/29 - 0s - 2ms/step - loss: 24.1740 - val_loss: 21.3940
Epoch 35/100
29/29 - 0s - 2ms/step - loss: 23.8150 - val_loss: 22.6209
Epoch 36/100
29/29 - 0s - 2ms/step - loss: 23.0814 - val_loss: 20.2912
Epoch 37/100
29/29 - 0s - 2ms/step - loss: 24.6657 - val_loss: 20.1914
Epoch 38/100
29/29 - 0s - 2ms/step - loss: 22.5256 - val_loss: 23.8493
Epoch 39/100
29/29 - 0s - 2ms/step - loss: 23.7618 - val_loss: 18.7513
Epoch 40/100
29/29 - 0s - 2ms/step - loss: 21.4497 - val_loss: 19.5247
Epoch 41/100
29/29 - 0s - 3ms/step - loss: 21.5971 - val_loss: 21.5775
Epoch 42/100
29/29 - 0s - 2ms/step - loss: 20.4313 - val_loss: 22.0884
Epoch 43/100
29/29 - 0s - 3ms/step - loss: 19.2948 - val_loss: 24.9522
Epoch 44/100
29/29 - 0s - 2ms/step - loss: 19.4016 - val_loss: 20.8655
Epoch 45/100
29/29 - 0s - 2ms/step - loss: 19.4381 - val_loss: 17.4887
Epoch 46/100
29/29 - 0s - 2ms/step - loss: 18.3159 - val_loss: 18.4966
Epoch 47/100
29/29 - 0s - 2ms/step - loss: 19.5452 - val_loss: 18.1085
Epoch 48/100
29/29 - 0s - 2ms/step - loss: 18.8574 - val_loss: 24.7144
Epoch 49/100
29/29 - 0s - 2ms/step - loss: 18.6106 - val_loss: 16.7349
Epoch 50/100
29/29 - 0s - 3ms/step - loss: 17.9938 - val_loss: 18.8823
Epoch 51/100
29/29 - 0s - 2ms/step - loss: 17.8886 - val_loss: 21.2976
Epoch 52/100
29/29 - 0s - 3ms/step - loss: 17.5096 - val_loss: 18.4291
Epoch 53/100
29/29 - 0s - 2ms/step - loss: 18.0848 - val_loss: 16.9283
Epoch 54/100
29/29 - 0s - 2ms/step - loss: 16.6499 - val_loss: 16.9862
Epoch 55/100
29/29 - 0s - 3ms/step - loss: 15.9985 - val_loss: 15.6950
Epoch 56/100
29/29 - 0s - 2ms/step - loss: 16.3760 - val_loss: 17.0190
Epoch 57/100
29/29 - 0s - 2ms/step - loss: 15.9415 - val_loss: 15.7556
Epoch 58/100
29/29 - 0s - 2ms/step - loss: 16.9758 - val_loss: 17.4961
Epoch 59/100
29/29 - 0s - 2ms/step - loss: 15.9057 - val_loss: 19.3391
Epoch 60/100
29/29 - 0s - 3ms/step - loss: 15.4342 - val_loss: 17.2335
Epoch 61/100
29/29 - 0s - 2ms/step - loss: 15.2903 - val_loss: 18.4660
Epoch 62/100
29/29 - 0s - 2ms/step - loss: 16.9667 - val_loss: 25.7023
Epoch 63/100
29/29 - 0s - 2ms/step - loss: 16.3248 - val_loss: 17.6406
Epoch 64/100
29/29 - 0s - 2ms/step - loss: 16.1061 - val_loss: 15.1885
Epoch 65/100
29/29 - 0s - 2ms/step - loss: 15.5771 - val_loss: 20.2104
Epoch 66/100
29/29 - 0s - 2ms/step - loss: 14.8449 - val_loss: 16.5546
Epoch 67/100
29/29 - 0s - 2ms/step - loss: 16.2176 - val_loss: 22.0275
Epoch 68/100
29/29 - 0s - 2ms/step - loss: 17.0906 - val_loss: 18.3122
Epoch 69/100
29/29 - 0s - 2ms/step - loss: 13.8533 - val_loss: 16.1338
Epoch 70/100
29/29 - 0s - 2ms/step - loss: 13.7118 - val_loss: 15.6151
Epoch 71/100
29/29 - 0s - 2ms/step - loss: 13.6908 - val_loss: 16.2278
Epoch 72/100
29/29 - 0s - 2ms/step - loss: 13.9051 - val_loss: 14.7793
Epoch 73/100
29/29 - 0s - 3ms/step - loss: 14.8877 - val_loss: 15.4212
Epoch 74/100
29/29 - 0s - 2ms/step - loss: 13.6389 - val_loss: 16.5605
Epoch 75/100
29/29 - 0s - 2ms/step - loss: 13.3870 - val_loss: 15.0122
Epoch 76/100
29/29 - 0s - 2ms/step - loss: 13.1050 - val_loss: 16.3902
Epoch 77/100
29/29 - 0s - 2ms/step - loss: 14.0577 - val_loss: 14.4562
Epoch 78/100
29/29 - 0s - 2ms/step - loss: 14.1512 - val_loss: 16.3574
Epoch 79/100
29/29 - 0s - 2ms/step - loss: 13.6939 - val_loss: 15.7759
Epoch 80/100
29/29 - 0s - 2ms/step - loss: 15.7456 - val_loss: 16.8295
Epoch 81/100
29/29 - 0s - 2ms/step - loss: 14.9691 - val_loss: 30.6202
Epoch 82/100
29/29 - 0s - 2ms/step - loss: 14.7739 - val_loss: 17.6892
Epoch 83/100
29/29 - 0s - 2ms/step - loss: 12.7692 - val_loss: 15.6318
Epoch 84/100
29/29 - 0s - 2ms/step - loss: 13.8757 - val_loss: 15.8196
Epoch 85/100
29/29 - 0s - 2ms/step - loss: 13.7749 - val_loss: 14.7266
Epoch 86/100
29/29 - 0s - 2ms/step - loss: 13.6292 - val_loss: 14.2137
Epoch 87/100
29/29 - 0s - 2ms/step - loss: 13.2147 - val_loss: 15.3150
Epoch 88/100
29/29 - 0s - 2ms/step - loss: 12.8846 - val_loss: 14.1025
Epoch 89/100
29/29 - 0s - 2ms/step - loss: 12.9533 - val_loss: 19.8894
Epoch 90/100
29/29 - 0s - 2ms/step - loss: 12.8992 - val_loss: 14.4168
Epoch 91/100
29/29 - 0s - 2ms/step - loss: 12.3908 - val_loss: 14.8977
Epoch 92/100
29/29 - 0s - 2ms/step - loss: 12.0453 - val_loss: 13.2136
Epoch 93/100
29/29 - 0s - 2ms/step - loss: 12.0688 - val_loss: 14.5646
Epoch 94/100
29/29 - 0s - 2ms/step - loss: 12.4879 - val_loss: 15.6037
Epoch 95/100
29/29 - 0s - 2ms/step - loss: 12.7281 - val_loss: 22.0638
Epoch 96/100
29/29 - 0s - 2ms/step - loss: 12.9152 - val_loss: 13.2394
Epoch 97/100
29/29 - 0s - 3ms/step - loss: 12.1444 - val_loss: 19.3323
Epoch 98/100
29/29 - 0s - 3ms/step - loss: 13.1372 - val_loss: 21.4272
Epoch 99/100
29/29 - 0s - 2ms/step - loss: 12.3546 - val_loss: 15.3565
Epoch 100/100
29/29 - 0s - 2ms/step - loss: 12.8693 - val_loss: 15.5556