<a href="https://cognitiveclass.ai"><img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DL0101EN-SkillsNetwork/images/IDSN-logo.png" width="400"> </a>

# Regression Models with Keras

Estimated time needed: **45** mins

## Introduction

As we discussed in the videos, despite the popularity of more powerful libraries such as PyToch and TensorFlow, they are not easy to use and have a steep learning curve. So, for people who are just starting to learn deep learning, there is no better library to use other than the Keras library. 

Keras is a high-level API for building deep learning models. It has gained favor for its ease of use and syntactic simplicity facilitating fast development. As you will see in this lab and the other labs in this course, building a very complex deep learning network can be achieved with Keras with only few lines of code. You will appreciate Keras even more, once you learn how to build deep models using PyTorch and TensorFlow in the other courses.

So, in this lab, you will learn how to use the Keras library to build a regression model.

앞서 영상에서 설명했듯이, PyTorch나 TensorFlow와 같은 강력한 라이브러리들이 인기를 얻고 있지만, 사용하기 쉽지 않고 학습 곡선이 가파릅니다. 따라서 딥러닝을 처음 배우는 사람들에게는 Keras 라이브러리보다 더 좋은 선택은 없습니다.

Keras는 딥러닝 모델 구축을 위한 고수준 API입니다. 사용 편의성과 간결한 구문 덕분에 빠른 개발이 가능하여 많은 사랑을 받고 있습니다. 이 실습과 이 강좌의 다른 실습에서 보겠지만, Keras를 사용하면 단 몇 줄의 코드로 매우 복잡한 딥러닝 네트워크를 구축할 수 있습니다. 다른 강좌에서 PyTorch와 TensorFlow를 사용하여 딥 모델을 구축하는 방법을 배우고 나면 Keras의 장점을 더욱 실감하게 될 것입니다.

이번 실습에서는 Keras 라이브러리를 사용하여 회귀 모델을 구축하는 방법을 배우게 됩니다.

## Objectives for this Notebook    
* How to use the Keras library to build a regression model
* Download and clean the data set
* Build a neural network
* Train and test the network     

## 이 노트북의 목표
* Keras 라이브러리를 사용하여 회귀 모델을 구축하는 방법
* 데이터셋 다운로드 및 정리
* 신경망 구축
* 신경망 학습 및 테스트

<h2>Table of Contents</h2>


<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 4>
1. <a href="#Download-and-Clean-the-Data-Set">Download and Clean the Data Set</a><br>
2. <a href="#Import-Keras-Packages">Import Keras Packages</a><br>
3. <a href="#Build-a-Neural-Network">Build a Neural Network</a><br>
4. <a href="#Train-and-Test-the-Network">Train and Test the Network</a><br>  

</font>
</div>

Let's start by importing the <em>pandas</em> and the Numpy libraries.

In [1]:
# All Libraries required for this lab are listed below. 

!pip install numpy==2.0.2
!pip install pandas==2.2.2
!pip install tensorflow_cpu==2.18.0

Collecting numpy==2.0.2
  Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 97.4 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-2.0.2
Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas==2.2.2) (2024.2)
Collecting tzdata>=2022.7 (from pandas==2.2.2)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 67.6 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-2.2.2 tzdata-2025.3
Collecting tensorflow_cpu==2.18.0
  Downloading tensorflow_cpu-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting absl-py>=1.0.0 (from tensorflow_cpu==2.18.0)
  Downloading absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow_cpu==2.18.0)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow_cpu==2.18.0)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow_cpu==2.18.0)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google-pasta>=0.1.1 (from tensorflow_cpu==2.18.0)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow_cpu==2.18.0)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow_cpu==2.18.0)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (24.2)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 (from tensorflow_cpu==2.18.0)
  Downloading protobuf-5.29.5-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.32.3)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (75.8.0)
Requirement already satisfied: six>=1.12.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow_cpu==2.18.0)
  Downloading termcolor-3.2.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (4.12.2)
Collecting wrapt>=1.11.0 (from tensorflow_cpu==2.18.0)
  Downloading wrapt-2.0.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (9.0 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow_cpu==2.18.0)
  Downloading grpcio-1.76.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.7 kB)
Collecting tensorboard<2.19,>=2.18 (from tensorflow_cpu==2.18.0)
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Collecting keras>=3.5.0 (from tensorflow_cpu==2.18.0)
  Downloading keras-3.13.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from tensorflow_cpu==2.18.0) (2.0.2)
Collecting h5py>=3.11.0 (from tensorflow_cpu==2.18.0)
  Downloading h5py-3.15.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting ml-dtypes<0.5.0,>=0.4.0 (from tensorflow_cpu==2.18.0)
  Downloading ml_dtypes-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/conda/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow_cpu==2.18.0) (0.45.1)
Collecting rich (from keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading rich-14.2.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading optree-0.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (34 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow_cpu==2.18.0) (2024.12.14)
Collecting markdown>=2.6.8 (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0)
  Downloading markdown-3.10-py3-none-any.whl.metadata (5.1 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0)
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0)
  Downloading werkzeug-3.1.4-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: markupsafe>=2.1.1 in /opt/conda/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow_cpu==2.18.0) (3.0.2)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich->keras>=3.5.0->tensorflow_cpu==2.18.0) (2.19.1)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow_cpu==2.18.0)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow_cpu-2.18.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (230.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.3/230.3 MB 28.8 MB/s eta 0:00:0000:0100:01
Downloading absl_py-2.3.1-py3-none-any.whl (135 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading grpcio-1.76.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 35.8 MB/s eta 0:00:00
Downloading h5py-3.15.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 32.5 MB/s eta 0:00:00
Downloading keras-3.13.0-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 52.6 MB/s eta 0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 39.9 MB/s eta 0:00:0000:0100:01
Downloading ml_dtypes-0.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 50.8 MB/s eta 0:00:00
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading protobuf-5.29.5-cp38-abi3-manylinux2014_x86_64.whl (319 kB)
Downloading tensorboard-2.18.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 39.0 MB/s eta 0:00:00
Downloading termcolor-3.2.0-py3-none-any.whl (7.7 kB)
Downloading wrapt-2.0.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (121 kB)
Downloading markdown-3.10-py3-none-any.whl (107 kB)
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 101.5 MB/s eta 0:00:00
Downloading werkzeug-3.1.4-py3-none-any.whl (224 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (408 kB)
Downloading rich-14.2.0-py3-none-any.whl (243 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: namex, libclang, flatbuffers, wrapt, werkzeug, termcolor, tensorboard-data-server, protobuf, optree, opt-einsum, ml-dtypes, mdurl, markdown, h5py, grpcio, google-pasta, gast, astunparse, absl-py, tensorboard, markdown-it-py, rich, keras, tensorflow_cpu
Successfully installed absl-py-2.3.1 astunparse-1.6.3 flatbuffers-25.12.19 gast-0.7.0 google-pasta-0.2.0 grpcio-1.76.0 h5py-3.15.1 keras-3.13.0 libclang-18.1.1 markdown-3.10 markdown-it-py-4.0.0 mdurl-0.1.2 ml-dtypes-0.4.1 namex-0.1.0 opt-einsum-3.4.0 optree-0.18.0 protobuf-5.29.5 rich-14.2.0 tensorboard-2.18.0 tensorboard-data-server-0.7.2 tensorflow_cpu-2.18.0 termcolor-3.2.0 werkzeug-3.1.4 wrapt-2.0.1

#### To use Keras, you will also need to install a backend framework – such as TensorFlow.

If you install TensorFlow 2.16 or above, it will install Keras by default.

We are using the CPU version of tensorflow since we are dealing with smaller datasets. 
You may install the GPU version of tensorflow on your machine to accelarate the processing of larger datasets

#### Keras를 사용하려면 TensorFlow와 같은 백엔드 프레임워크도 설치해야 합니다.

TensorFlow 2.16 이상 버전을 설치하면 Keras가 기본적으로 설치됩니다.

본 예제에서는 소규모 데이터셋을 다루기 때문에 TensorFlow의 CPU 버전을 사용합니다.

더 큰 규모의 데이터셋 처리를 가속화하려면 TensorFlow의 GPU 버전을 설치할 수 있습니다.

#### Suppress the tensorflow warning messages
We use the following code to  suppress the warning messages due to use of CPU architechture for tensoflow.

You may want to **comment out** these lines if you are using the GPU architechture

#### TensorFlow 경고 메시지 억제
TensorFlow에서 CPU 아키텍처를 사용하기 때문에 발생하는 경고 메시지를 억제하기 위해 다음 코드를 사용합니다.

GPU 아키텍처를 사용하는 경우, 이 줄들을 **주석 처리**하는 것이 좋습니다.

In [2]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [3]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

/opt/conda/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

We will be playing around with the same dataset that we used in the videos.

<strong>The dataset is about the compressive strength of different samples of concrete based on the volumes of the different ingredients that were used to make them. Ingredients include:</strong>

* Cement
* Blast furnace slag
* Fly ash
* Water
* Superplasticizer
* Coarse aggregate
* Fine aggregate
* 
우리는 영상에서 사용했던 것과 동일한 데이터셋을 가지고 실험을 진행할 것입니다.

<strong>이 데이터셋은 콘크리트를 만드는 데 사용된 다양한 재료의 부피에 따른 여러 콘크리트 시료의 압축 강도에 관한 것입니다. 재료는 다음과 같습니다.</strong>

* 시멘트
* 고로 슬래그
* 플라이애시
* 물
* 고성능 감수제
* 굵은 골재
* 잔골재

## Download and Clean the Data Set

Let's download the data and read it into a <em>pandas</em> dataframe.

In [4]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

So the first concrete sample has 540 cubic meter of cement, 0 cubic meter of blast furnace slag, 0 cubic meter of fly ash, 162 cubic meter of water, 2.5 cubic meter of superplaticizer, 1040 cubic meter of coarse aggregate, 676 cubic meter of fine aggregate. Such a concrete mix which is 28 days old, has a compressive strength of 79.99 MPa. 

첫 번째 콘크리트 시료는 시멘트 540 세제곱미터, 고로 슬래그 0 세제곱미터, 플라이애시 0 세제곱미터, 물 162 세제곱미터, 경화제 2.5 세제곱미터, 굵은 골재 1040 세제곱미터, 잔골재 676 세제곱미터로 구성되어 있습니다. 이 콘크리트는 28일 경과 후 압축강도가 79.99 MPa입니다.

#### Let's check how many data points we have
데이터 포인트가 몇 개인지 확인해 봅시다.

In [5]:
concrete_data.shape

(1030, 9)

So, there are approximately 1000 samples to train our model on. Because of the few samples, we have to be careful not to overfit the training data.

따라서 모델 학습에 사용할 샘플은 약 1000개입니다. 샘플 수가 적기 때문에 학습 데이터에 과적합되지 않도록 주의해야 합니다.

Let's check the dataset for any missing values.
데이터셋에 누락된 값이 있는지 확인해 보겠습니다.

In [6]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [8]:
#비어있는 값 확인
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

데이터가 매우 깔끔하고 모델 구축에 바로 사용할 수 있을 것 같습니다.

#### Split data into predictors and target

The target variable in this problem is the concrete sample strength. Therefore, our predictors will be all the other columns.

이 문제에서 목표 변수는 콘크리트 시료 강도입니다. 따라서 예측 변수는 나머지 모든 열이 될 것입니다.

In [9]:
concrete_data_columns = concrete_data.columns

In [10]:
# predictors 강도 제외 하여 등록,  target 강도 값 만 (정답지)
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

<a id="item2"></a>

Let's do a quick sanity check of the predictors and the target dataframes.
예측 변수와 목표 데이터프레임이 제대로 설정되었는지 간단히 확인해 보겠습니다

In [11]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [12]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Finally, the last step is to normalize the data by substracting the mean and dividing by the standard deviation. 

마지막으로, 평균을 빼고 표준편차로 나누어 데이터를 정규화하는 것이 마지막 단계입니다.

In [13]:
# 정규화 수싱 
# predictors - predictors.mean(): 각 데이터에서 해당 컬럼의 평균을 뺍니다. 이렇게 하면 데이터의 중심이 $0$이 됩니다.
# / predictors.std(): 그 결과를 표준편차로 나눕니다. 이렇게 하면 데이터가 퍼져 있는 정도(분산)가 일정하게 맞춰집니다.
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

Let's save the number of predictors to *n_cols* since we will need this number when building our network.

In [14]:
n_cols = predictors_norm.shape[1] # number of predictors

<a id="item1"></a>

##  Import Keras Packages

##### Let's import the rest of the packages from the Keras library that we will need to build our regression model.


## Keras 패키지 가져오기

##### 회귀 모델을 구축하는 데 필요한 나머지 Keras 패키지를 가져오겠습니다.

In [15]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

## Build a Neural Network

Let's define a function that defines our regression model for us so that we can conveniently call it to create our model.

회귀 모델을 정의하는 함수를 만들어, 필요할 때 편리하게 호출하여 모델을 생성할 수 있도록 해봅시다.

In [16]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

The above function create a model that has two hidden layers, each of 50 hidden units.

위 함수는 각각 50개의 은닉 유닛을 가진 두 개의 은닉층을 포함하는 모델을 생성합니다.

## Train and Test the Network

Let's call the function now to create our model.

이제 함수를 호출하여 모델을 생성해 보겠습니다.

In [17]:
# build the model
model = regression_model()

Next, we will train and test the model at the same time using the *fit* method. We will leave out 30% of the data for validation and we will train the model for 100 epochs.

다음으로, `fit` 메서드를 사용하여 모델을 동시에 학습하고 테스트하겠습니다. 데이터의 30%는 검증용으로 남겨두고, 100 에포크 동안 모델을 학습시킬 것입니다.

In [18]:
# fit the model 학습시작
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - 53ms/step - loss: 1643.7867 - val_loss: 1150.1542
Epoch 2/100
23/23 - 0s - 7ms/step - loss: 1515.5005 - val_loss: 1025.9899
Epoch 3/100
23/23 - 0s - 7ms/step - loss: 1292.0680 - val_loss: 819.7567
Epoch 4/100
23/23 - 0s - 8ms/step - loss: 956.1341 - val_loss: 566.1074
Epoch 5/100
23/23 - 0s - 8ms/step - loss: 591.0280 - val_loss: 343.7136
Epoch 6/100
23/23 - 0s - 8ms/step - loss: 339.5241 - val_loss: 227.8185
Epoch 7/100
23/23 - 0s - 7ms/step - loss: 254.3953 - val_loss: 194.6491
Epoch 8/100
23/23 - 0s - 7ms/step - loss: 234.8766 - val_loss: 188.2235
Epoch 9/100
23/23 - 0s - 7ms/step - loss: 221.2611 - val_loss: 185.5286
Epoch 10/100
23/23 - 0s - 8ms/step - loss: 210.8227 - val_loss: 178.1671
Epoch 11/100
23/23 - 0s - 6ms/step - loss: 202.3593 - val_loss: 175.3005
Epoch 12/100
23/23 - 0s - 7ms/step - loss: 196.0915 - val_loss: 171.5662
Epoch 13/100
23/23 - 0s - 7ms/step - loss: 189.7011 - val_loss: 171.6763
Epoch 14/100
23/23 - 0s - 7ms/step - loss: 184.6079 - val_loss: 169.2907
Epoch 15/100
23/23 - 0s - 6ms/step - loss: 179.8566 - val_loss: 166.1771
Epoch 16/100
23/23 - 0s - 7ms/step - loss: 175.9050 - val_loss: 165.7480
Epoch 17/100
23/23 - 0s - 7ms/step - loss: 171.9553 - val_loss: 163.0769
Epoch 18/100
23/23 - 0s - 8ms/step - loss: 169.1880 - val_loss: 160.4624
Epoch 19/100
23/23 - 0s - 7ms/step - loss: 165.6547 - val_loss: 161.0450
Epoch 20/100
23/23 - 0s - 6ms/step - loss: 163.0678 - val_loss: 157.6848
Epoch 21/100
23/23 - 0s - 6ms/step - loss: 160.6601 - val_loss: 157.6973
Epoch 22/100
23/23 - 0s - 6ms/step - loss: 157.7294 - val_loss: 156.9101
Epoch 23/100
23/23 - 0s - 6ms/step - loss: 155.4201 - val_loss: 153.2097
Epoch 24/100
23/23 - 0s - 6ms/step - loss: 153.9210 - val_loss: 152.7547
Epoch 25/100
23/23 - 0s - 8ms/step - loss: 151.6631 - val_loss: 150.8123
Epoch 26/100
23/23 - 0s - 7ms/step - loss: 149.2114 - val_loss: 151.7982
Epoch 27/100
23/23 - 0s - 6ms/step - loss: 147.0657 - val_loss: 149.8913
Epoch 28/100
23/23 - 0s - 6ms/step - loss: 145.4336 - val_loss: 148.2283
Epoch 29/100
23/23 - 0s - 6ms/step - loss: 143.9047 - val_loss: 148.1820
Epoch 30/100
23/23 - 0s - 6ms/step - loss: 141.8834 - val_loss: 148.4604
Epoch 31/100
23/23 - 0s - 7ms/step - loss: 141.4160 - val_loss: 147.7574
Epoch 32/100
23/23 - 0s - 7ms/step - loss: 138.9143 - val_loss: 145.7812
Epoch 33/100
23/23 - 0s - 6ms/step - loss: 137.2590 - val_loss: 144.9766
Epoch 34/100
23/23 - 0s - 6ms/step - loss: 135.6241 - val_loss: 146.2749
Epoch 35/100
23/23 - 0s - 6ms/step - loss: 134.0688 - val_loss: 145.0174
Epoch 36/100
23/23 - 0s - 6ms/step - loss: 132.4994 - val_loss: 145.8453
Epoch 37/100
23/23 - 0s - 6ms/step - loss: 131.2181 - val_loss: 144.7267
Epoch 38/100
23/23 - 0s - 7ms/step - loss: 129.1577 - val_loss: 144.9601
Epoch 39/100
23/23 - 0s - 7ms/step - loss: 127.9522 - val_loss: 143.3631
Epoch 40/100
23/23 - 0s - 7ms/step - loss: 126.8554 - val_loss: 143.9165
Epoch 41/100
23/23 - 0s - 7ms/step - loss: 125.1921 - val_loss: 141.6923
Epoch 42/100
23/23 - 0s - 7ms/step - loss: 123.8606 - val_loss: 144.7843
Epoch 43/100
23/23 - 0s - 7ms/step - loss: 123.7022 - val_loss: 142.9167
Epoch 44/100
23/23 - 0s - 7ms/step - loss: 121.3273 - val_loss: 145.2793
Epoch 45/100
23/23 - 0s - 7ms/step - loss: 119.8325 - val_loss: 142.5424
Epoch 46/100
23/23 - 0s - 7ms/step - loss: 118.2321 - val_loss: 140.7453
Epoch 47/100
23/23 - 0s - 7ms/step - loss: 116.7997 - val_loss: 143.6660
Epoch 48/100
23/23 - 0s - 6ms/step - loss: 114.6879 - val_loss: 141.7815
Epoch 49/100
23/23 - 0s - 7ms/step - loss: 113.1019 - val_loss: 141.7628
Epoch 50/100
23/23 - 0s - 7ms/step - loss: 111.9783 - val_loss: 141.2496
Epoch 51/100
23/23 - 0s - 7ms/step - loss: 109.7752 - val_loss: 136.4178
Epoch 52/100
23/23 - 0s - 6ms/step - loss: 108.5567 - val_loss: 143.1193
Epoch 53/100
23/23 - 0s - 6ms/step - loss: 106.8252 - val_loss: 136.8138
Epoch 54/100
23/23 - 0s - 6ms/step - loss: 104.6471 - val_loss: 137.3589
Epoch 55/100
23/23 - 0s - 6ms/step - loss: 102.6684 - val_loss: 136.2210
Epoch 56/100
23/23 - 0s - 7ms/step - loss: 100.7187 - val_loss: 134.7615
Epoch 57/100
23/23 - 0s - 6ms/step - loss: 98.6678 - val_loss: 133.0928
Epoch 58/100
23/23 - 0s - 6ms/step - loss: 96.4563 - val_loss: 132.6617
Epoch 59/100
23/23 - 0s - 6ms/step - loss: 94.7918 - val_loss: 130.6554
Epoch 60/100
23/23 - 0s - 7ms/step - loss: 92.7541 - val_loss: 130.2271
Epoch 61/100
23/23 - 0s - 7ms/step - loss: 90.0568 - val_loss: 127.1085
Epoch 62/100
23/23 - 0s - 7ms/step - loss: 88.5034 - val_loss: 129.8897
Epoch 63/100
23/23 - 0s - 6ms/step - loss: 86.0090 - val_loss: 124.1872
Epoch 64/100
23/23 - 0s - 8ms/step - loss: 83.8788 - val_loss: 124.3393
Epoch 65/100
23/23 - 0s - 6ms/step - loss: 82.0726 - val_loss: 121.4767
Epoch 66/100
23/23 - 0s - 6ms/step - loss: 80.5985 - val_loss: 119.4353
Epoch 67/100
23/23 - 0s - 6ms/step - loss: 78.0699 - val_loss: 119.2348
Epoch 68/100
23/23 - 0s - 7ms/step - loss: 76.0928 - val_loss: 115.8690
Epoch 69/100
23/23 - 0s - 6ms/step - loss: 73.6413 - val_loss: 113.0513
Epoch 70/100
23/23 - 0s - 6ms/step - loss: 71.4690 - val_loss: 115.0756
Epoch 71/100
23/23 - 0s - 7ms/step - loss: 70.6894 - val_loss: 107.7378
Epoch 72/100
23/23 - 0s - 7ms/step - loss: 67.8613 - val_loss: 110.9238
Epoch 73/100
23/23 - 0s - 6ms/step - loss: 66.3954 - val_loss: 108.0828
Epoch 74/100
23/23 - 0s - 7ms/step - loss: 65.0813 - val_loss: 104.2992
Epoch 75/100
23/23 - 0s - 7ms/step - loss: 62.9121 - val_loss: 105.4488
Epoch 76/100
23/23 - 0s - 6ms/step - loss: 61.4040 - val_loss: 102.9581
Epoch 77/100
23/23 - 0s - 6ms/step - loss: 58.7004 - val_loss: 102.5084
Epoch 78/100
23/23 - 0s - 7ms/step - loss: 57.4482 - val_loss: 104.8502
Epoch 79/100
23/23 - 0s - 7ms/step - loss: 55.6815 - val_loss: 99.8329
Epoch 80/100
23/23 - 0s - 7ms/step - loss: 53.9342 - val_loss: 100.5038
Epoch 81/100
23/23 - 0s - 7ms/step - loss: 52.6960 - val_loss: 99.8735
Epoch 82/100
23/23 - 0s - 7ms/step - loss: 51.8521 - val_loss: 102.4610
Epoch 83/100
23/23 - 0s - 6ms/step - loss: 50.3384 - val_loss: 95.4383
Epoch 84/100
23/23 - 0s - 6ms/step - loss: 49.9410 - val_loss: 95.3508
Epoch 85/100
23/23 - 0s - 6ms/step - loss: 48.4806 - val_loss: 93.2646
Epoch 86/100
23/23 - 0s - 6ms/step - loss: 47.1188 - val_loss: 95.1662
Epoch 87/100
23/23 - 0s - 6ms/step - loss: 46.6643 - val_loss: 99.6227
Epoch 88/100
23/23 - 0s - 7ms/step - loss: 45.5207 - val_loss: 94.7553
Epoch 89/100
23/23 - 0s - 6ms/step - loss: 44.5732 - val_loss: 91.8967
Epoch 90/100
23/23 - 0s - 6ms/step - loss: 43.2329 - val_loss: 94.1053
Epoch 91/100
23/23 - 0s - 7ms/step - loss: 42.6151 - val_loss: 90.8274
Epoch 92/100
23/23 - 0s - 7ms/step - loss: 41.6197 - val_loss: 96.3448
Epoch 93/100
23/23 - 0s - 6ms/step - loss: 41.4415 - val_loss: 98.9640
Epoch 94/100
23/23 - 0s - 6ms/step - loss: 41.1432 - val_loss: 100.5944
Epoch 95/100
23/23 - 0s - 6ms/step - loss: 39.8539 - val_loss: 98.4671
Epoch 96/100
23/23 - 0s - 6ms/step - loss: 39.1769 - val_loss: 99.9580
Epoch 97/100
23/23 - 0s - 6ms/step - loss: 38.0392 - val_loss: 93.9883
Epoch 98/100
23/23 - 0s - 6ms/step - loss: 37.8296 - val_loss: 97.2665
Epoch 99/100
23/23 - 0s - 6ms/step - loss: 37.4441 - val_loss: 97.8685
Epoch 100/100
23/23 - 0s - 6ms/step - loss: 36.8393 - val_loss: 97.2817

<strong>You can refer to this [link](https://keras.io/models/sequential/) to learn about other functions that you can use for prediction or evaluation.</strong>

<strong>예측 또는 평가에 사용할 수 있는 다른 기능에 대해 알아보려면 [링크](https://keras.io/models/sequential/)를 참조하세요.</strong>

Feel free to vary the following and note what impact each change has on the model's performance:

1. Increase or decreate number of neurons in hidden layers
2. Add more hidden layers
3. Increase number of epochs

다음 사항들을 자유롭게 변경해 보고, 각 변경 사항이 모델 성능에 미치는 영향을 기록해 보세요.

1. 은닉층의 뉴런 수 증가 또는 감소
2. 은닉층 추가
3. 에포크 수 증가

<h3>Practice Exercise 1</h3>

Now using the same dateset,try to recreate regression model featuring five hidden layers, each with 50 nodes and ReLU activation functions, a single output layer, optimized using the Adam optimizer.

이제 동일한 데이터셋을 사용하여, 각각 50개의 노드와 ReLU 활성화 함수를 가진 5개의 은닉층, 하나의 출력층을 특징으로 하는 회귀 모델을 Adam 최적화 알고리즘을 이용하여 재현해 보십시오.

In [22]:
# Write your code here
# define regression model
def regression_model_ex1():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

model_ex1 = regression_model_ex1()
model_ex1.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 2s - 77ms/step - loss: 1618.7977 - val_loss: 1009.9272
Epoch 2/100
23/23 - 0s - 9ms/step - loss: 851.8482 - val_loss: 352.6949
Epoch 3/100
23/23 - 0s - 9ms/step - loss: 380.8155 - val_loss: 222.3689
Epoch 4/100
23/23 - 0s - 9ms/step - loss: 243.9307 - val_loss: 194.9511
Epoch 5/100
23/23 - 0s - 8ms/step - loss: 212.5431 - val_loss: 192.5480
Epoch 6/100
23/23 - 0s - 9ms/step - loss: 190.5640 - val_loss: 196.4058
Epoch 7/100
23/23 - 0s - 8ms/step - loss: 172.6999 - val_loss: 187.8992
Epoch 8/100
23/23 - 0s - 8ms/step - loss: 157.2294 - val_loss: 177.9468
Epoch 9/100
23/23 - 0s - 8ms/step - loss: 144.6865 - val_loss: 172.2459
Epoch 10/100
23/23 - 0s - 8ms/step - loss: 127.8600 - val_loss: 181.0207
Epoch 11/100
23/23 - 0s - 8ms/step - loss: 116.1362 - val_loss: 172.9752
Epoch 12/100
23/23 - 0s - 8ms/step - loss: 102.5368 - val_loss: 148.8842
Epoch 13/100
23/23 - 0s - 8ms/step - loss: 90.2023 - val_loss: 158.9243
Epoch 14/100
23/23 - 0s - 7ms/step - loss: 78.3780 - val_loss: 143.5573
Epoch 15/100
23/23 - 0s - 7ms/step - loss: 70.1878 - val_loss: 148.8560
Epoch 16/100
23/23 - 0s - 8ms/step - loss: 61.8744 - val_loss: 152.4913
Epoch 17/100
23/23 - 0s - 8ms/step - loss: 56.5407 - val_loss: 153.5070
Epoch 18/100
23/23 - 0s - 8ms/step - loss: 52.0170 - val_loss: 157.6502
Epoch 19/100
23/23 - 0s - 8ms/step - loss: 48.5873 - val_loss: 154.4588
Epoch 20/100
23/23 - 0s - 8ms/step - loss: 45.4606 - val_loss: 166.9832
Epoch 21/100
23/23 - 0s - 8ms/step - loss: 45.4106 - val_loss: 142.0862
Epoch 22/100
23/23 - 0s - 8ms/step - loss: 46.3962 - val_loss: 179.6735
Epoch 23/100
23/23 - 0s - 8ms/step - loss: 39.6145 - val_loss: 170.0362
Epoch 24/100
23/23 - 0s - 8ms/step - loss: 37.5451 - val_loss: 183.4773
Epoch 25/100
23/23 - 0s - 7ms/step - loss: 35.1183 - val_loss: 162.9919
Epoch 26/100
23/23 - 0s - 7ms/step - loss: 34.1490 - val_loss: 163.8788
Epoch 27/100
23/23 - 0s - 8ms/step - loss: 33.9126 - val_loss: 179.5163
Epoch 28/100
23/23 - 0s - 8ms/step - loss: 32.6942 - val_loss: 167.1993
Epoch 29/100
23/23 - 0s - 8ms/step - loss: 32.8613 - val_loss: 192.4925
Epoch 30/100
23/23 - 0s - 8ms/step - loss: 29.5292 - val_loss: 170.0115
Epoch 31/100
23/23 - 0s - 7ms/step - loss: 28.4749 - val_loss: 162.0246
Epoch 32/100
23/23 - 0s - 8ms/step - loss: 27.6093 - val_loss: 187.0242
Epoch 33/100
23/23 - 0s - 8ms/step - loss: 26.7861 - val_loss: 182.9220
Epoch 34/100
23/23 - 0s - 8ms/step - loss: 25.7479 - val_loss: 180.0242
Epoch 35/100
23/23 - 0s - 8ms/step - loss: 28.4375 - val_loss: 216.2862
Epoch 36/100
23/23 - 0s - 8ms/step - loss: 26.4269 - val_loss: 171.0228
Epoch 37/100
23/23 - 0s - 7ms/step - loss: 24.7919 - val_loss: 166.5128
Epoch 38/100
23/23 - 0s - 7ms/step - loss: 23.6825 - val_loss: 197.8101
Epoch 39/100
23/23 - 0s - 8ms/step - loss: 24.0088 - val_loss: 159.1998
Epoch 40/100
23/23 - 0s - 8ms/step - loss: 22.5807 - val_loss: 145.3311
Epoch 41/100
23/23 - 0s - 8ms/step - loss: 23.3497 - val_loss: 173.2451
Epoch 42/100
23/23 - 0s - 7ms/step - loss: 20.5717 - val_loss: 172.1473
Epoch 43/100
23/23 - 0s - 8ms/step - loss: 19.9344 - val_loss: 196.0432
Epoch 44/100
23/23 - 0s - 8ms/step - loss: 20.4292 - val_loss: 161.1486
Epoch 45/100
23/23 - 0s - 9ms/step - loss: 19.2094 - val_loss: 161.7512
Epoch 46/100
23/23 - 0s - 7ms/step - loss: 19.0337 - val_loss: 162.2288
Epoch 47/100
23/23 - 0s - 7ms/step - loss: 19.4395 - val_loss: 176.3150
Epoch 48/100
23/23 - 0s - 7ms/step - loss: 18.2063 - val_loss: 165.0240
Epoch 49/100
23/23 - 0s - 7ms/step - loss: 18.3196 - val_loss: 162.4843
Epoch 50/100
23/23 - 0s - 8ms/step - loss: 19.1914 - val_loss: 111.5237
Epoch 51/100
23/23 - 0s - 7ms/step - loss: 18.0851 - val_loss: 168.3899
Epoch 52/100
23/23 - 0s - 7ms/step - loss: 17.2877 - val_loss: 135.2511
Epoch 53/100
23/23 - 0s - 7ms/step - loss: 17.3235 - val_loss: 164.3462
Epoch 54/100
23/23 - 0s - 7ms/step - loss: 16.6803 - val_loss: 129.1274
Epoch 55/100
23/23 - 0s - 8ms/step - loss: 16.9607 - val_loss: 133.0408
Epoch 56/100
23/23 - 0s - 7ms/step - loss: 17.4610 - val_loss: 149.4600
Epoch 57/100
23/23 - 0s - 7ms/step - loss: 15.8799 - val_loss: 156.9900
Epoch 58/100
23/23 - 0s - 7ms/step - loss: 16.2651 - val_loss: 137.7088
Epoch 59/100
23/23 - 0s - 7ms/step - loss: 15.0465 - val_loss: 120.7836
Epoch 60/100
23/23 - 0s - 7ms/step - loss: 15.8170 - val_loss: 142.9594
Epoch 61/100
23/23 - 0s - 7ms/step - loss: 16.7604 - val_loss: 150.3242
Epoch 62/100
23/23 - 0s - 7ms/step - loss: 16.1677 - val_loss: 152.5169
Epoch 63/100
23/23 - 0s - 7ms/step - loss: 15.5694 - val_loss: 120.8555
Epoch 64/100
23/23 - 0s - 8ms/step - loss: 15.4986 - val_loss: 144.1548
Epoch 65/100
23/23 - 0s - 7ms/step - loss: 14.5926 - val_loss: 127.2533
Epoch 66/100
23/23 - 0s - 7ms/step - loss: 14.9822 - val_loss: 151.8024
Epoch 67/100
23/23 - 0s - 7ms/step - loss: 15.0685 - val_loss: 161.1178
Epoch 68/100
23/23 - 0s - 7ms/step - loss: 14.8637 - val_loss: 122.8797
Epoch 69/100
23/23 - 0s - 8ms/step - loss: 14.5638 - val_loss: 129.7388
Epoch 70/100
23/23 - 0s - 7ms/step - loss: 13.9092 - val_loss: 131.1872
Epoch 71/100
23/23 - 0s - 7ms/step - loss: 13.6651 - val_loss: 114.4434
Epoch 72/100
23/23 - 0s - 7ms/step - loss: 14.0759 - val_loss: 142.5186
Epoch 73/100
23/23 - 0s - 7ms/step - loss: 15.5002 - val_loss: 133.4804
Epoch 74/100
23/23 - 0s - 7ms/step - loss: 14.9183 - val_loss: 119.3092
Epoch 75/100
23/23 - 0s - 7ms/step - loss: 13.2645 - val_loss: 148.9532
Epoch 76/100
23/23 - 0s - 7ms/step - loss: 13.4690 - val_loss: 158.0555
Epoch 77/100
23/23 - 0s - 7ms/step - loss: 13.2359 - val_loss: 143.4781
Epoch 78/100
23/23 - 0s - 7ms/step - loss: 13.3692 - val_loss: 140.2875
Epoch 79/100
23/23 - 0s - 8ms/step - loss: 13.3109 - val_loss: 124.1284
Epoch 80/100
23/23 - 0s - 8ms/step - loss: 13.2294 - val_loss: 147.8519
Epoch 81/100
23/23 - 0s - 8ms/step - loss: 12.6885 - val_loss: 133.5440
Epoch 82/100
23/23 - 0s - 8ms/step - loss: 12.2466 - val_loss: 159.1130
Epoch 83/100
23/23 - 0s - 7ms/step - loss: 13.8813 - val_loss: 157.3308
Epoch 84/100
23/23 - 0s - 7ms/step - loss: 13.4785 - val_loss: 148.3582
Epoch 85/100
23/23 - 0s - 8ms/step - loss: 13.2519 - val_loss: 179.3366
Epoch 86/100
23/23 - 0s - 8ms/step - loss: 14.7215 - val_loss: 166.0920
Epoch 87/100
23/23 - 0s - 8ms/step - loss: 14.0880 - val_loss: 165.1771
Epoch 88/100
23/23 - 0s - 8ms/step - loss: 13.8753 - val_loss: 159.0219
Epoch 89/100
23/23 - 0s - 7ms/step - loss: 12.9623 - val_loss: 159.7005
Epoch 90/100
23/23 - 0s - 8ms/step - loss: 11.5246 - val_loss: 133.8120
Epoch 91/100
23/23 - 0s - 7ms/step - loss: 12.0535 - val_loss: 146.6861
Epoch 92/100
23/23 - 0s - 8ms/step - loss: 12.5973 - val_loss: 151.0161
Epoch 93/100
23/23 - 0s - 7ms/step - loss: 12.1038 - val_loss: 145.4470
Epoch 94/100
23/23 - 0s - 7ms/step - loss: 12.2373 - val_loss: 118.3255
Epoch 95/100
23/23 - 0s - 7ms/step - loss: 13.7580 - val_loss: 131.2711
Epoch 96/100
23/23 - 0s - 7ms/step - loss: 11.8742 - val_loss: 123.2805
Epoch 97/100
23/23 - 0s - 7ms/step - loss: 11.3076 - val_loss: 135.3082
Epoch 98/100
23/23 - 0s - 7ms/step - loss: 11.0241 - val_loss: 125.7711
Epoch 99/100
23/23 - 0s - 7ms/step - loss: 12.9688 - val_loss: 156.0278
Epoch 100/100
23/23 - 0s - 7ms/step - loss: 13.1643 - val_loss: 162.5161

Double-click <b>here</b> for the solution.

<!-- Your answer is below:
def regression_model():
    input_colm = predictors_norm.shape[1] # Number of input features
    # create model
    model = Sequential()
    model.add(Input(shape=(input_colm,)))  # Set the number of input features 
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu')) 
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))  
    model.add(Dense(1))  # Output layer
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

-->

<h3>Practice Exercise 2</h3>

 Train and evaluate the model simultaneously using the fit() method by reserving 10% of the data for validation and training the model for 100 epochs

fit() 메서드를 사용하여 모델의 학습과 평가를 동시에 진행합니다. 이때 데이터의 10%는 검증용으로 남겨두고, 모델은 100 에포크 동안 학습합니다.

In [23]:
# Write your code here
model_ex1 = regression_model_ex1()
model_ex1.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

Epoch 1/100
29/29 - 2s - 70ms/step - loss: 1541.4938 - val_loss: 1004.3360
Epoch 2/100
29/29 - 0s - 7ms/step - loss: 701.6469 - val_loss: 288.5514
Epoch 3/100
29/29 - 0s - 8ms/step - loss: 235.8602 - val_loss: 190.9176
Epoch 4/100
29/29 - 0s - 8ms/step - loss: 193.4423 - val_loss: 188.1973
Epoch 5/100
29/29 - 0s - 7ms/step - loss: 183.6914 - val_loss: 186.2300
Epoch 6/100
29/29 - 0s - 7ms/step - loss: 169.8430 - val_loss: 170.7611
Epoch 7/100
29/29 - 0s - 7ms/step - loss: 157.8956 - val_loss: 156.6520
Epoch 8/100
29/29 - 0s - 7ms/step - loss: 146.2568 - val_loss: 149.5247
Epoch 9/100
29/29 - 0s - 7ms/step - loss: 134.7916 - val_loss: 137.5549
Epoch 10/100
29/29 - 0s - 7ms/step - loss: 118.7292 - val_loss: 126.5048
Epoch 11/100
29/29 - 0s - 7ms/step - loss: 104.3318 - val_loss: 112.5267
Epoch 12/100
29/29 - 0s - 7ms/step - loss: 91.2471 - val_loss: 101.2956
Epoch 13/100
29/29 - 0s - 7ms/step - loss: 80.7699 - val_loss: 79.7466
Epoch 14/100
29/29 - 0s - 7ms/step - loss: 72.7826 - val_loss: 75.4833
Epoch 15/100
29/29 - 0s - 7ms/step - loss: 63.2850 - val_loss: 65.7376
Epoch 16/100
29/29 - 0s - 7ms/step - loss: 59.1125 - val_loss: 58.9186
Epoch 17/100
29/29 - 0s - 7ms/step - loss: 56.0687 - val_loss: 52.4162
Epoch 18/100
29/29 - 0s - 6ms/step - loss: 50.0987 - val_loss: 51.1419
Epoch 19/100
29/29 - 0s - 7ms/step - loss: 47.9724 - val_loss: 48.2172
Epoch 20/100
29/29 - 0s - 7ms/step - loss: 44.9357 - val_loss: 40.3119
Epoch 21/100
29/29 - 0s - 6ms/step - loss: 43.0993 - val_loss: 36.3101
Epoch 22/100
29/29 - 0s - 7ms/step - loss: 41.1720 - val_loss: 36.6139
Epoch 23/100
29/29 - 0s - 6ms/step - loss: 38.1380 - val_loss: 31.5775
Epoch 24/100
29/29 - 0s - 7ms/step - loss: 34.3271 - val_loss: 32.0468
Epoch 25/100
29/29 - 0s - 7ms/step - loss: 32.3720 - val_loss: 31.3462
Epoch 26/100
29/29 - 0s - 7ms/step - loss: 31.4678 - val_loss: 32.1306
Epoch 27/100
29/29 - 0s - 7ms/step - loss: 30.6303 - val_loss: 29.2689
Epoch 28/100
29/29 - 0s - 7ms/step - loss: 28.8744 - val_loss: 33.3131
Epoch 29/100
29/29 - 0s - 6ms/step - loss: 27.3782 - val_loss: 37.4118
Epoch 30/100
29/29 - 0s - 7ms/step - loss: 26.3767 - val_loss: 28.1413
Epoch 31/100
29/29 - 0s - 7ms/step - loss: 24.6252 - val_loss: 27.8376
Epoch 32/100
29/29 - 0s - 6ms/step - loss: 24.9593 - val_loss: 27.7283
Epoch 33/100
29/29 - 0s - 6ms/step - loss: 24.7513 - val_loss: 26.1608
Epoch 34/100
29/29 - 0s - 6ms/step - loss: 24.0174 - val_loss: 28.5467
Epoch 35/100
29/29 - 0s - 7ms/step - loss: 22.3997 - val_loss: 25.8983
Epoch 36/100
29/29 - 0s - 7ms/step - loss: 21.0593 - val_loss: 27.2026
Epoch 37/100
29/29 - 0s - 7ms/step - loss: 21.5740 - val_loss: 25.1019
Epoch 38/100
29/29 - 0s - 6ms/step - loss: 20.3265 - val_loss: 33.7884
Epoch 39/100
29/29 - 0s - 7ms/step - loss: 21.1649 - val_loss: 32.3548
Epoch 40/100
29/29 - 0s - 7ms/step - loss: 20.4053 - val_loss: 24.6958
Epoch 41/100
29/29 - 0s - 7ms/step - loss: 20.9664 - val_loss: 29.5382
Epoch 42/100
29/29 - 0s - 7ms/step - loss: 19.6930 - val_loss: 24.3448
Epoch 43/100
29/29 - 0s - 6ms/step - loss: 20.4154 - val_loss: 41.4225
Epoch 44/100
29/29 - 0s - 7ms/step - loss: 19.6427 - val_loss: 26.1459
Epoch 45/100
29/29 - 0s - 7ms/step - loss: 18.0324 - val_loss: 23.6164
Epoch 46/100
29/29 - 0s - 6ms/step - loss: 17.7189 - val_loss: 24.2481
Epoch 47/100
29/29 - 0s - 6ms/step - loss: 18.5535 - val_loss: 23.3527
Epoch 48/100
29/29 - 0s - 6ms/step - loss: 24.8134 - val_loss: 27.8483
Epoch 49/100
29/29 - 0s - 7ms/step - loss: 19.9571 - val_loss: 22.6224
Epoch 50/100
29/29 - 0s - 7ms/step - loss: 17.2595 - val_loss: 24.0584
Epoch 51/100
29/29 - 0s - 6ms/step - loss: 16.5605 - val_loss: 24.4293
Epoch 52/100
29/29 - 0s - 7ms/step - loss: 15.9419 - val_loss: 25.9134
Epoch 53/100
29/29 - 0s - 7ms/step - loss: 16.6734 - val_loss: 23.6297
Epoch 54/100
29/29 - 0s - 6ms/step - loss: 15.7748 - val_loss: 22.6295
Epoch 55/100
29/29 - 0s - 6ms/step - loss: 15.8179 - val_loss: 21.7778
Epoch 56/100
29/29 - 0s - 7ms/step - loss: 16.0330 - val_loss: 22.3269
Epoch 57/100
29/29 - 0s - 7ms/step - loss: 15.8043 - val_loss: 21.6660
Epoch 58/100
29/29 - 0s - 6ms/step - loss: 15.9622 - val_loss: 20.9548
Epoch 59/100
29/29 - 0s - 7ms/step - loss: 15.3482 - val_loss: 20.5886
Epoch 60/100
29/29 - 0s - 6ms/step - loss: 15.7077 - val_loss: 20.5829
Epoch 61/100
29/29 - 0s - 7ms/step - loss: 14.9342 - val_loss: 21.6063
Epoch 62/100
29/29 - 0s - 7ms/step - loss: 15.7948 - val_loss: 19.4278
Epoch 63/100
29/29 - 0s - 7ms/step - loss: 16.6338 - val_loss: 22.7223
Epoch 64/100
29/29 - 0s - 6ms/step - loss: 16.1728 - val_loss: 20.6169
Epoch 65/100
29/29 - 0s - 7ms/step - loss: 14.5159 - val_loss: 27.4626
Epoch 66/100
29/29 - 0s - 7ms/step - loss: 14.9921 - val_loss: 20.5902
Epoch 67/100
29/29 - 0s - 6ms/step - loss: 14.2629 - val_loss: 19.9242
Epoch 68/100
29/29 - 0s - 7ms/step - loss: 15.4684 - val_loss: 25.9712
Epoch 69/100
29/29 - 0s - 7ms/step - loss: 15.0289 - val_loss: 20.8869
Epoch 70/100
29/29 - 0s - 6ms/step - loss: 15.8604 - val_loss: 22.4882
Epoch 71/100
29/29 - 0s - 7ms/step - loss: 15.1199 - val_loss: 22.0320
Epoch 72/100
29/29 - 0s - 6ms/step - loss: 15.1370 - val_loss: 19.5572
Epoch 73/100
29/29 - 0s - 7ms/step - loss: 14.3063 - val_loss: 18.8558
Epoch 74/100
29/29 - 0s - 6ms/step - loss: 13.8631 - val_loss: 23.0714
Epoch 75/100
29/29 - 0s - 6ms/step - loss: 13.4579 - val_loss: 21.8956
Epoch 76/100
29/29 - 0s - 7ms/step - loss: 14.4710 - val_loss: 23.3431
Epoch 77/100
29/29 - 0s - 6ms/step - loss: 13.7679 - val_loss: 18.8865
Epoch 78/100
29/29 - 0s - 7ms/step - loss: 14.2326 - val_loss: 19.1032
Epoch 79/100
29/29 - 0s - 7ms/step - loss: 16.7384 - val_loss: 21.4535
Epoch 80/100
29/29 - 0s - 6ms/step - loss: 14.4526 - val_loss: 21.2194
Epoch 81/100
29/29 - 0s - 7ms/step - loss: 12.9571 - val_loss: 19.5115
Epoch 82/100
29/29 - 0s - 7ms/step - loss: 13.3049 - val_loss: 24.5859
Epoch 83/100
29/29 - 0s - 6ms/step - loss: 15.4299 - val_loss: 20.6811
Epoch 84/100
29/29 - 0s - 6ms/step - loss: 14.8598 - val_loss: 19.7886
Epoch 85/100
29/29 - 0s - 6ms/step - loss: 13.3931 - val_loss: 21.2898
Epoch 86/100
29/29 - 0s - 7ms/step - loss: 13.6213 - val_loss: 23.2575
Epoch 87/100
29/29 - 0s - 7ms/step - loss: 13.0313 - val_loss: 19.3773
Epoch 88/100
29/29 - 0s - 6ms/step - loss: 12.5572 - val_loss: 19.2096
Epoch 89/100
29/29 - 0s - 7ms/step - loss: 12.5498 - val_loss: 19.3583
Epoch 90/100
29/29 - 0s - 6ms/step - loss: 12.6546 - val_loss: 18.8556
Epoch 91/100
29/29 - 0s - 6ms/step - loss: 13.2712 - val_loss: 21.7086
Epoch 92/100
29/29 - 0s - 6ms/step - loss: 12.6723 - val_loss: 22.3881
Epoch 93/100
29/29 - 0s - 6ms/step - loss: 12.1613 - val_loss: 20.5435
Epoch 94/100
29/29 - 0s - 6ms/step - loss: 13.7990 - val_loss: 29.5665
Epoch 95/100
29/29 - 0s - 6ms/step - loss: 12.4938 - val_loss: 18.4896
Epoch 96/100
29/29 - 0s - 7ms/step - loss: 14.0204 - val_loss: 20.5537
Epoch 97/100
29/29 - 0s - 7ms/step - loss: 12.2824 - val_loss: 19.8846
Epoch 98/100
29/29 - 0s - 7ms/step - loss: 12.2950 - val_loss: 18.5137
Epoch 99/100
29/29 - 0s - 7ms/step - loss: 11.2351 - val_loss: 19.3475
Epoch 100/100
29/29 - 0s - 6ms/step - loss: 11.5116 - val_loss: 17.7011

Double-click <b>here</b> for the solution.

<!-- Your answer is below:
# build the model
model = regression_model()
model.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

-->

Based on the results, we notice that:

- Adding more hidden layers to the model increases its capacity to learn and represent complex relationships within the data. This allows the model to better identify, as a result, the model becomes more effective at fitting the training data and potentially improving its predictions.
- By reducing the proportion of data set aside for validation and using a larger portion for training, the model has access to more examples to learn from. This additional training data helps the model improve its understanding of the underlying trends, which can lead to better overall performance.  

분석 결과를 바탕으로 다음과 같은 사실을 확인할 수 있습니다.

- 모델에 은닉층을 추가하면 데이터 내의 복잡한 관계를 학습하고 표현하는 능력이 향상됩니다. 이를 통해 모델은 관계를 더 잘 파악할 수 있게 되어, 훈련 데이터에 더 효과적으로 적응하고 예측 성능을 향상시킬 수 있습니다.

- 검증에 사용하는 데이터 비율을 줄이고 훈련에 더 많은 데이터를 활용하면 모델은 더 많은 예제를 학습에 사용할 수 있습니다. 이러한 추가 훈련 데이터는 모델이 근본적인 추세를 더 잘 이해하도록 도와주며, 결과적으로 전반적인 성능 향상으로 이어질 수 있습니다.

### Thank you for completing this lab!

This notebook was created by [Alex Aklson](https://www.linkedin.com/in/aklson/). I hope you found this lab interesting and educational. Feel free to contact me if you have any questions!

<!--
## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2024-11-20  | 3.0  | Aman  |  Updated the library versions to current |
| 2020-09-21  | 2.0  | Srishti  |  Migrated Lab to Markdown and added to course repo in GitLab |



<hr>

## <h3 align="center"> © IBM Corporation. All rights reserved. <h3/>

## <h3 align="center"> &#169; IBM Corporation. All rights reserved. <h3/>